name: Publish Package to npmjs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Rebuild
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.VERCEL_REBUILD }}
          method: 'POST'
          
      - name: Update Data
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.UPDATE_DATA }}
          method: 'GET'
          
